### ISSUE TITLE
ENM Travis Fail 

### ISSUE THREAD

**Issue by sbottaro** [srnas/barnaba#22]
@giopina , ENM tests fail with Python 2.7 and 3.6 but not 3.5. Could it be related to precision/phase issues?

**Comment by giopina** [comment]
There was indeed a phase issue (now I fixed it using the same trick we use when printing the eigenvectors), but the real problem was a bug in the test_enm script (I was using a P-ENM with a cutoff of 0.9, which lead to 16 null modes, which are degenerate, so they were giving unconsistent results.

I'm creating a pull request with the fixed code
