### ISSUE TITLE
BUG annotate conversion to dotbracket

### ISSUE THREAD

**Issue by sreisser** [srnas/barnaba#31]
Hi,
I found a case where an A-G and a C-U pair end up as basepairs in the dotbracket annotation (1S72). The annotations look fine, so there seems to be a bug in the conversion to dotbracket.
Cheers
Sabine

**Comment by vmlynsky** [comment]
Hi Sabine,

… do you have the latest baRNAba version somewhere on workstations/felisca?

I would like to perform one quick test, but I was not able to install the recent version (because of problem with mdtraj).

Thanks for reply.
Vojtech.

On 24 Apr 2018, at 1:36 PM, sreisser <notifications@github.com> wrote:

Hi,
I found a case where an A-G and a C-U pair end up as basepairs in the dotbracket annotation (1S72). The annotations look fine, so there seems to be a bug in the conversion to dotbracket.
Cheers
Sabine

**Comment by sbottaro** [comment]
Hi @sreisser, 
thanks! the bug should be fixed now. I think the bug affected only complex structures (don't really know why)m so you should get the same results on simple MD trajectories. Could you please cross-check that everything works as it should?
